#!/usr/bin/env python3
"""board.py: the task board, generated from the headers of work/tasks/*.md.

    python3 .claude/workflow/board.py            regenerate work/BOARD.md + work/board.html
    python3 .claude/workflow/board.py --open     … and open the visual board in the browser
    python3 .claude/workflow/board.py --check    warnings only (used by the session-start check)
    python3 .claude/workflow/board.py --next-id  print the next free T-NNN

The cards are the single source of truth. BOARD.md (read by Claude, kept small) and
board.html (for the owner, never read by Claude) are generated: never edit them.
Standard library only.
"""
import html, json, os, re, subprocess, sys
from datetime import date, datetime, timedelta

ROOT = os.environ.get("CLAUDE_PROJECT_DIR") or os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
TASKS = os.path.join(ROOT, "work", "tasks")
STATUSES = ["triage", "backlog", "ready", "in-progress", "in-review", "blocked", "done", "dropped"]
ACTIVE = ["in-progress", "in-review", "blocked", "ready"]
TYPES = ["bug", "feature", "chore", "spike", "idea"]
PRIORITIES = ["P0", "P1", "P2", "P3"]


def conf():
    c = {"wip": 2, "p0": 1, "triage_days": 7}
    p = os.path.join(ROOT, "work", "board.conf")
    if os.path.exists(p):
        for line in open(p):
            m = re.match(r"\s*(\w+)\s*=\s*(\d+)", line)
            if m:
                c[m.group(1)] = int(m.group(2))
    return c


def parse_date(s):
    try:
        return datetime.strptime(s.strip(), "%Y-%m-%d").date()
    except Exception:
        return None


def load():
    items, problems = [], []
    if not os.path.isdir(TASKS):
        return items, problems
    for name in sorted(os.listdir(TASKS)):
        if not re.match(r"T-\d+.*\.md$", name):
            continue
        text = open(os.path.join(TASKS, name), encoding="utf-8", errors="replace").read()
        m = re.match(r"---\n(.*?)\n---", text, re.S)
        it = {"file": name, "id": re.match(r"(T-\d+)", name).group(1)}
        if not m:
            problems.append(f"{name}: no header; add one (see .claude/workflow/templates/task.md)")
            it.update(title=name[:-3], status="backlog", type="chore", priority="P2")
        else:
            for line in m.group(1).splitlines():
                k, _, v = line.partition(":")
                if _:
                    it[k.strip()] = re.split(r"\s+#", v, maxsplit=1)[0].strip()  # "# comment", not URL#fragment
        it.setdefault("title", name[:-3])
        it["status"] = it.get("status", "backlog").lower()
        it["type"] = it.get("type", "feature").lower()
        it["priority"] = it.get("priority", "P2").upper()
        if it["status"] not in STATUSES:
            problems.append(f"{name}: unknown status '{it['status']}'")
        items.append(it)
    return items, problems


def by_priority(it):
    p = it["priority"]
    return (PRIORITIES.index(p) if p in PRIORITIES else 9, it["id"])


def warnings(items, c):
    w = []
    wip = [i for i in items if i["status"] == "in-progress"]
    if len(wip) > c["wip"]:
        w.append(f"WIP {len(wip)} in progress (limit {c['wip']}): finish before starting more")
    p0 = [i for i in items if i["priority"] == "P0" and i["status"] not in ("done", "dropped")]
    if len(p0) > c["p0"]:
        w.append(f"{len(p0)} open P0s (cap {c['p0']}): re-prioritise")
    elif p0:
        w.append(f"P0 open: {p0[0]['id']} {p0[0]['title']}: do it first")
    old = [i for i in items if i["status"] == "triage" and (parse_date(i.get("created", "")) or date.today()) < date.today() - timedelta(days=c["triage_days"])]
    if old:
        w.append(f"{len(old)} item(s) in triage > {c['triage_days']} days: give them a priority (/orient)")
    for i in items:
        if i["status"] == "blocked":
            w.append(f"blocked: {i['id']} {i['title']} ({i.get('blocked_by', 'reason on card')})")
    return w


def cell(s, n=70):
    s = (s or "").replace("|", "/")
    return s if len(s) <= n else s[: n - 1] + "…"


def board_md(items, c, problems):
    count = {s: sum(1 for i in items if i["status"] == s) for s in STATUSES}
    out = [
        "# Board",
        "",
        "<!-- GENERATED by .claude/workflow/board.py from the headers of work/tasks/*.md.",
        "Never edit this file: change a card's header, then run the script. Visual board: work/board.html -->",
        "",
        f"{date.today()} · **{count['in-progress']} in progress** (WIP limit {c['wip']}) · {count['in-review']} in review · "
        f"{count['blocked']} blocked · {count['ready']} ready · {count['backlog']} backlog · {count['triage']} triage · {count['done']} done",
        "",
    ]
    for w in warnings(items, c) + problems:
        out.append(f"> ⚠ {w}")
    active = sorted([i for i in items if i["status"] in ACTIVE], key=lambda i: (ACTIVE.index(i["status"]),) + by_priority(i))
    out += ["", "## Active", "", "| Task | Type | P | Who | Status | Branch | Locks |", "| --- | --- | --- | --- | --- | --- | --- |"]
    shown_ready = 0
    for i in active:
        if i["status"] == "ready":
            shown_ready += 1
            if shown_ready > 8:
                continue
        out.append(f"| {i['id']} · {cell(i['title'])} | {i['type']} | {i['priority']} | {i.get('owner', '')} | {i['status']} | "
                   f"{('`' + i['branch'] + '`') if i.get('branch') else ''} | {cell(i.get('locks', ''), 50)} |")
    if shown_ready > 8:
        out.append(f"| … {shown_ready - 8} more ready | | | | | | |")
    if not active:
        out.append("| (nothing active) | | | | | | |")
    tri = [i for i in items if i["status"] == "triage"]
    if tri:
        out += ["", "## Triage (needs a type check and a priority)"] + [f"- {i['id']} · {i['type']} · {cell(i['title'], 90)}" for i in tri[:10]]
    nxt = sorted([i for i in items if i["status"] == "backlog"], key=by_priority)
    if nxt:
        out += ["", "## Next up (backlog, by priority)"] + [f"- {i['id']} · {i['priority']} · {i['type']} · {cell(i['title'], 90)}" for i in nxt[:6]]
        if len(nxt) > 6:
            out.append(f"- … {len(nxt) - 6} more in the backlog (work/board.html)")
    ms = {}
    for i in items:
        if i.get("milestone") and i["status"] != "dropped":
            d, t = ms.get(i["milestone"], (0, 0))
            ms[i["milestone"]] = (d + (i["status"] == "done"), t + 1)
    if ms:
        out += ["", "## Milestones"] + [f"- {k}: {d}/{t} done" for k, (d, t) in sorted(ms.items())]
    out += ["", f"Done and dropped items are not listed ({count['done']} done): see work/board.html.", ""]
    return "\n".join(out)


def link(p):
    p = p.strip()
    if re.match(r"https?://", p):
        return p
    return os.path.relpath(os.path.join(ROOT, p), os.path.join(ROOT, "work"))


def board_html(items, c, problems):
    today = date.today()
    data = []
    for i in items:
        cr, st, dn = (parse_date(i.get(k, "")) for k in ("created", "started", "done"))
        cycle = (dn - (st or cr)).days if dn and (st or cr) else None
        age = (today - (st or cr)).days if (st or cr) and not dn else None
        data.append({
            "id": i["id"], "title": i["title"], "type": i["type"], "status": i["status"], "priority": i["priority"],
            "owner": i.get("owner", ""), "milestone": i.get("milestone", ""), "file": "tasks/" + i["file"],
            "mockups": [link(m) for m in re.split(r"[,\s]+", i.get("mockup", "")) if m],
            "links": [link(m) for m in re.split(r"[,\s]+", i.get("links", "")) if m],
            "done": i.get("done", ""), "cycle": cycle, "age": age, "blocked_by": i.get("blocked_by", ""),
        })
    # throughput: items done per ISO week, last 8 weeks
    weeks = []
    for k in range(7, -1, -1):
        start = today - timedelta(days=today.weekday() + 7 * k)
        n = sum(1 for d in data if d["done"] and start <= (parse_date(d["done"]) or date.min) < start + timedelta(days=7))
        weeks.append({"label": start.strftime("%d %b"), "n": n})
    cycles = [d["cycle"] for d in data if d["cycle"] is not None and d["done"] and parse_date(d["done"]) >= today - timedelta(days=30)]
    meta = {
        "project": os.path.basename(ROOT), "generated": datetime.now().strftime("%Y-%m-%d %H:%M"), "wip": c["wip"],
        "warnings": warnings(items, c) + problems, "weeks": weeks,
        "cycle": round(sum(cycles) / len(cycles), 1) if cycles else None,
    }
    return TEMPLATE.replace("__DATA__", json.dumps(data)).replace("__META__", json.dumps(meta)).replace("__TITLE__", html.escape(meta["project"]))


def next_id(items):
    n = max([int(i["id"][2:]) for i in items] + [0]) + 1
    return f"T-{n:03d}"


def main():
    items, problems = load()
    c = conf()
    if "--next-id" in sys.argv:
        print(next_id(items)); return
    if "--check" in sys.argv:
        nohead = [p for p in problems if "no header" in p]
        other = [p for p in problems if "no header" not in p]
        if nohead:
            other.insert(0, f"{len(nohead)} card(s) have no header (older cards?): /adopt-workflow or /tidy adds them")
        for w in warnings(items, c) + other[:3]:
            print(w)
        return
    os.makedirs(os.path.join(ROOT, "work"), exist_ok=True)
    bp = os.path.join(ROOT, "work", "BOARD.md")
    if os.path.exists(bp) and "GENERATED by .claude/workflow/board.py" not in open(bp, errors="replace").read(600):
        print("board: work/BOARD.md is hand-written, so it was NOT overwritten. /adopt-workflow migrates it; "
              "until then only work/board.html is generated.")
    else:
        open(bp, "w").write(board_md(items, c, problems))
    open(os.path.join(ROOT, "work", "board.html"), "w").write(board_html(items, c, problems))
    open_n = sum(1 for i in items if i["status"] not in ("done", "dropped"))
    print(f"board: {len(items)} items ({open_n} open) → work/BOARD.md, work/board.html")
    if "--open" in sys.argv:
        subprocess.run(["open" if sys.platform == "darwin" else "xdg-open", os.path.join(ROOT, "work", "board.html")])


TEMPLATE = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>__TITLE__ · Board</title>
<style>
:root{--bg:#f6f7f9;--panel:#fff;--ink:#16181d;--mute:#667085;--line:#e4e7ec;--chip:#f2f4f7;
--bug:#d92d20;--feature:#2e90fa;--chore:#667085;--spike:#9e77ed;--idea:#12b76a;--p0:#d92d20;--p1:#f79009;--p2:#667085;--p3:#98a2b3;--ok:#12b76a;--warn:#b54708;--warnbg:#fffaeb}
@media (prefers-color-scheme:dark){:root{--bg:#0e1116;--panel:#161b22;--ink:#e6edf3;--mute:#8b949e;--line:#30363d;--chip:#21262d;--warnbg:#2d2206;--warn:#f5b54c}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",Inter,sans-serif}
header{padding:16px 20px 8px;display:flex;flex-wrap:wrap;gap:12px 24px;align-items:baseline}
h1{font-size:18px;margin:0}.sub{color:var(--mute);font-size:12px}
.stats{display:flex;flex-wrap:wrap;gap:10px;padding:0 20px 8px}
.stat{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:8px 12px;min-width:110px}
.stat b{display:block;font-size:20px}.stat span{color:var(--mute);font-size:12px}
.spark{display:flex;align-items:flex-end;gap:3px;height:34px;margin-top:4px}.spark i{width:10px;background:var(--feature);border-radius:2px 2px 0 0;opacity:.8}
.warn{margin:4px 20px;padding:8px 12px;border-radius:8px;background:var(--warnbg);color:var(--warn);font-size:13px}
.bar{display:flex;flex-wrap:wrap;gap:8px;padding:8px 20px;align-items:center}
.bar input,.bar select{background:var(--panel);color:var(--ink);border:1px solid var(--line);border-radius:8px;padding:6px 8px;font:inherit}
#q{min-width:200px;flex:1;max-width:320px}.bar label{display:flex;gap:6px;align-items:center}
.ms{display:flex;flex-wrap:wrap;gap:10px;padding:4px 20px 8px}.m{font-size:12px;color:var(--mute);min-width:160px}
.m .track{height:6px;background:var(--line);border-radius:3px;margin-top:3px;overflow:hidden}.m .fill{height:100%;background:var(--ok)}
.cols{display:grid;grid-template-columns:repeat(6,minmax(205px,1fr));gap:12px;padding:8px 20px 24px;overflow-x:auto}
.col{background:var(--chip);border-radius:12px;padding:8px;min-height:120px}
.col h2{font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:var(--mute);margin:4px 6px 8px;display:flex;justify-content:space-between}
.col h2 .over{color:var(--p0)}
.card{display:block;cursor:pointer;background:var(--panel);border:1px solid var(--line);border-left:4px solid var(--c);border-radius:8px;padding:8px 10px;margin-bottom:8px;color:inherit;text-decoration:none}
.card:hover{border-color:var(--mute)}.card .t{font-weight:600;margin:2px 0 6px}
.row{display:flex;flex-wrap:wrap;gap:6px;align-items:center;font-size:11px;color:var(--mute)}
.chip{background:var(--chip);border-radius:999px;padding:1px 7px;color:var(--ink)}
.pri{font-weight:700}.P0{color:var(--p0)}.P1{color:var(--p1)}.P2{color:var(--p2)}.P3{color:var(--p3)}
.links a{color:var(--feature);text-decoration:none;margin-right:6px}.blk{color:var(--p0)}
.more{font-size:12px;color:var(--mute);text-align:center;cursor:pointer;padding:4px}
@media (max-width:700px){.cols{grid-template-columns:repeat(6,82vw)}}
</style></head><body>
<header><h1>__TITLE__</h1><span class="sub" id="gen"></span></header>
<div class="stats" id="stats"></div><div id="warns"></div>
<div class="ms" id="ms"></div>
<div class="bar"><input id="q" placeholder="Search title or T-NNN"><select id="type"><option value="">All types</option></select>
<select id="pri"><option value="">All priorities</option></select><select id="mile"><option value="">All milestones</option></select>
<label class="sub"><input type="checkbox" id="mock">has mock-up</label></div>
<div class="cols" id="cols"></div>
<script>
const D=__DATA__, M=__META__;
const COLS=[["triage","Triage"],["backlog","Backlog"],["ready","Ready"],["in-progress","In progress"],["in-review","In review"],["done","Done"]];
const TC={bug:"var(--bug)",feature:"var(--feature)",chore:"var(--chore)",spike:"var(--spike)",idea:"var(--idea)"};
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
let showAllDone=false;
$("#gen").textContent="generated "+M.generated+" · edit the cards, not this page";
const open=D.filter(d=>!["done","dropped"].includes(d.status));
const bugs=open.filter(d=>d.type==="bug");
const stat=(b,s,x="")=>`<div class="stat"><b>${b}</b><span>${s}</span>${x}</div>`;
$("#stats").innerHTML=stat(open.length,"open items")+stat(bugs.length,`open bugs · ${bugs.filter(b=>["P0","P1"].includes(b.priority)).length} P0/P1`)
 +stat(D.filter(d=>d.status==="in-progress").length+" / "+M.wip,"in progress / WIP limit")
 +stat(D.filter(d=>d.status==="done").length,"done")+stat(M.cycle??"–","avg cycle days (30 d)")
 +stat(M.weeks.reduce((a,w)=>a+w.n,0),"done in 8 weeks",`<div class="spark">${M.weeks.map(w=>`<i title="${w.label}: ${w.n}" style="height:${4+w.n*30/Math.max(1,...M.weeks.map(x=>x.n))}px"></i>`).join("")}</div>`);
$("#warns").innerHTML=M.warnings.map(w=>`<div class="warn">⚠ ${esc(w)}</div>`).join("");
const ms={};D.filter(d=>d.milestone&&d.status!=="dropped").forEach(d=>{ms[d.milestone]??=[0,0];ms[d.milestone][1]++;if(d.status==="done")ms[d.milestone][0]++});
$("#ms").innerHTML=Object.keys(ms).sort().map(k=>`<div class="m">${esc(k)} · ${ms[k][0]}/${ms[k][1]}<div class="track"><div class="fill" style="width:${100*ms[k][0]/ms[k][1]}%"></div></div></div>`).join("");
const fill=(id,vals)=>vals.forEach(v=>$(id).insertAdjacentHTML("beforeend",`<option>${esc(v)}</option>`));
fill("#type",[...new Set(D.map(d=>d.type))].sort());fill("#pri",["P0","P1","P2","P3"]);fill("#mile",Object.keys(ms).sort());
try{const s=JSON.parse(localStorage.getItem("board-filters")||"{}");for(const k in s){const e=$("#"+k);if(e){e.type==="checkbox"?e.checked=s[k]:e.value=s[k]}}}catch(e){}
function card(d){
 const age=d.status==="done"?(d.cycle!=null?`${d.cycle} d cycle`:""):(d.age!=null?`${d.age} d old`:"");
 const L=[...d.mockups.map((u,i)=>`<a href="${esc(u)}" target="_blank" onclick="event.stopPropagation()">🖼 mock-up${d.mockups.length>1?" "+(i+1):""}</a>`),...d.links.map(u=>`<a href="${esc(u)}" target="_blank" onclick="event.stopPropagation()">🔗 link</a>`)].join("");
 return `<div class="card" role="link" tabindex="0" title="Open ${d.id}" onclick="location.href='${esc(d.file)}'" style="--c:${TC[d.type]||"var(--chore)"}">
 <div class="row"><b>${d.id}</b><span class="pri ${d.priority}">${d.priority}</span><span class="chip">${esc(d.type)}</span>${d.owner?`<span>${esc(d.owner)}</span>`:""}${d.status==="blocked"?'<span class="blk">● blocked</span>':""}</div>
 <div class="t">${esc(d.title)}</div>
 <div class="row">${d.milestone?`<span>${esc(d.milestone)}</span>`:""}<span>${age}</span>${d.blocked_by?`<span class="blk">by ${esc(d.blocked_by)}</span>`:""}</div>
 ${L?`<div class="row links">${L}</div>`:""}</div>`}
function render(){
 const q=$("#q").value.toLowerCase(),t=$("#type").value,p=$("#pri").value,m=$("#mile").value,mk=$("#mock").checked;
 try{localStorage.setItem("board-filters",JSON.stringify({q:$("#q").value,type:t,pri:p,mile:m,mock:mk}))}catch(e){}
 const ok=d=>(!q||(d.id+" "+d.title).toLowerCase().includes(q))&&(!t||d.type===t)&&(!p||d.priority===p)&&(!m||d.milestone===m)&&(!mk||d.mockups.length);
 const pr=d=>["P0","P1","P2","P3"].indexOf(d.priority);
 $("#cols").innerHTML=COLS.map(([s,name])=>{
  let xs=D.filter(d=>(d.status===s||(s==="in-progress"&&d.status==="blocked"))&&ok(d));
  xs.sort(s==="done"?(a,b)=>(b.done||"").localeCompare(a.done||""):(a,b)=>pr(a)-pr(b)||a.id.localeCompare(b.id));
  const total=xs.length;if(s==="done"&&!showAllDone)xs=xs.slice(0,15);
  const over=s==="in-progress"&&total>M.wip;
  return `<div class="col"><h2><span>${name}</span><span class="${over?"over":""}">${total}${s==="in-progress"?" / "+M.wip:""}</span></h2>${xs.map(card).join("")}
  ${s==="done"&&total>15&&!showAllDone?`<div class="more" onclick="showAllDone=true;render()">show all ${total}</div>`:""}</div>`}).join("")}
["#q","#type","#pri","#mile","#mock"].forEach(s=>$(s).addEventListener("input",render));render();
</script></body></html>"""

if __name__ == "__main__":
    main()
